name: first workflow 
on: push
jobs:
        job1:
            runs-on: ubuntu-latest
            steps:
            - name: Step 1
              run: echo "hello from step 1"
            - name: Step 2
              run: echo "hello from step 2"
        job2:
           runs-on: ubuntu-latest
           steps:
           - name: Step 3
           run: echo "hello from final step "
        
         
