name: "Event info workflow"
on: push
jobs:
  event-info-job:
    runs-on: ubuntu-latest
    steps:
    - name:  "finding the event"
      run: echo "the event is ${{ github.event_name }}"
      
        
         
