name: "Event info workflow"
on:
  workflow_dispatch:
  push:

jobs:
  event-info-job:
    runs-on: ubuntu-latest
    steps:
    - name:  "finding the event"
      run: |
        echo "Workflow is executing on github self hosted runner"
        echo "Runner name:  $RUNNER_NAME"
        echo "Runner OS:  $RUNNER_OS"
        echo "Runner Architecture:  $RUNNER_ARCH"